server:
  servlet:
    #项目访问路径
    context-path: /wph
  port: 8088
  #提供HTTPS服务
#  ssl:
#    key-store: C:\Users\Administrator\mykeys.jks
#    key-store-password: DENGNING
#    key-password: DENGNING

spring:
  #JDBC连接数据库
  datasource:
    #mysql 8.0以上版本
    #driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://localhost:3306/wph?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8&useSSL=true
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wph?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
  #Redis缓存数据库
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: localhost
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1
        # 连接池中的最大空闲连接 默认 8
        max-idle: 8
        # 连接池中的最小空闲连接 默认 0
        min-idle: 0
  #热部署
  devtools:
    restart:
      enabled: true #设置开启热部署

logging:
   level:
     #日志打印级别,根组件打印警告信息
    root: warn
    #日志打印级别，mapper打印SQL语句
    hhxy.dn.wph: DEBUG
    #Spring security 日志
    org.springframework.security: DEBUG

#用户头像存放地址
UPLOAD_URL: E:\Vue_projects\vue14_test01\static\user\headIcon\

